---

language: python
services: docker

env:
  global:
    - ROLE_NAME: folding-at-home
  matrix:
    # Test defaults.
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10

install:
  - pip install ansible molecule yamllint ansible-lint docker
before_script:
  - cd ../
  - mv ansible-role-folding-at-home $ROLE_NAME
  - cd $ROLE_NAME

script:
  #- make all
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
